version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
    - location: scripts/delete_old_index.sh
      timeout: 5
      runas: root
    - location: scripts/create_index.sh
      timeout: 5
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 5
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 10
      runas: root
